import {
  GraduationCap,
  PenLine,
  Scale,
  Compass,
  TrendingUp,
  LayoutTemplate,
  Microscope,
  FileText,
  Workflow,
  BookOpen,
  Library,
  RefreshCcw,
  Hammer,
  Brain,
  Network,
  Swords,
  Layers,
  Clapperboard,
  Sparkles,
  Target,
  Map,
  Zap,
  Rocket,
  Linkedin,
  PenTool,
  Terminal,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  "graduation-cap": GraduationCap,
  "pen-line": PenLine,
  "scale": Scale,
  "compass": Compass,
  "trending-up": TrendingUp,
  "layout-template": LayoutTemplate,
  "microscope": Microscope,
  "file-text": FileText,
  "workflow": Workflow,
  "book-open": BookOpen,
  "library": Library,
  "refresh-ccw": RefreshCcw,
  "hammer": Hammer,
  "brain": Brain,
  "network": Network,
  "swords": Swords,
  "layers": Layers,
  "clapperboard": Clapperboard,
  "sparkles": Sparkles,
  "target": Target,
  "map": Map,
  "zap": Zap,
  "rocket": Rocket,
  "linkedin": Linkedin,
  "pen-tool": PenTool,
  "terminal": Terminal,
};

/** Returns the LucideIcon component for a given icon name. Falls back to Layers. */
export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? Layers;
}
